// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_web9ixZ5FEe6nunfPMqjlgaaF5Y5JH4',
    appId: '1:771227551793:web:8bf414a500db06d0afad10',
    messagingSenderId: '771227551793',
    projectId: 'sammitako-tiktok-final',
    authDomain: 'sammitako-tiktok-final.firebaseapp.com',
    storageBucket: 'sammitako-tiktok-final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI5s_MGfIl55FhnJAaX9sDmxUB-VKiz3s',
    appId: '1:771227551793:android:ba66c97fd3a7ab28afad10',
    messagingSenderId: '771227551793',
    projectId: 'sammitako-tiktok-final',
    storageBucket: 'sammitako-tiktok-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg_l2pVocqTgRUBVPwZAOGPOSzqq6cM9s',
    appId: '1:771227551793:ios:5d3fecfbc4954ec0afad10',
    messagingSenderId: '771227551793',
    projectId: 'sammitako-tiktok-final',
    storageBucket: 'sammitako-tiktok-final.firebasestorage.app',
    iosBundleId: 'com.example.tiktokFinal',
  );

}